project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
    - source: /docs/**/*
      translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%

preserve_hierarchy: true
